bitcoinNetwork: bsv

indexUnconfirmedTx: False

logLevel: Debug

logFileName: ./nexa.log

bitcoinNodeListenIP: 127.0.0.1

bitcoinNodeListenPort: 3000

endPointTLSListenIP: 127.0.0.1

endPointTLSListenPort: 9090

maxTxProcThreads: 80

maxBitcoinPeerCount: 10

unresponsivePeerConnTimeoutSecs: 180

acivatePeerDiscovery: True

staticPeerList: []

allegoryVendorSecretKey: 1435cf8e437d789eac332c3c66b2a51876e58c21db4b4da15488c3decb1a8b57

maxTMTBuilderThreads: 20

maxTMTQueueSize: 1024

txProcInputDependenciesWait: 240

txProcTimeoutSecs : 250

tlsCertificatePath : ./certificate.cert

tlsKeyfilePath : ./server.key

tlsCertificateStorePath : /opt/certstore
