bitcoinNetwork: bsv

logLevel: Debug

logFileName: ./debug.log

bitcoinNodeListenIP: 127.0.0.1

bitcoinNodeListenPort: 3000

endPointTLSListenIP: 127.0.0.1

endPointTLSListenPort: 9090

endPointHTTPSListenIP: 127.0.0.1

endPointHTTPSListenPort: 9091

maxBitcoinPeerCount: 10

unresponsivePeerConnTimeoutSecs: 600

acivatePeerDiscovery: True

staticPeerList: []

allegoryVendorSecretKey: 1435cf8e437d789eac332c3c66b2a51876e58c21db4b4da15488c3decb1a8b57

maxTMTBuilderThreads: 200

txProcInputDependenciesWait: 240

tlsCertificatePath: ./example.crt

tlsKeyfilePath: ./example.key

tlsCertificateStorePath: ./

neo4jUsername: neo4j

neo4jPassword: neo4j

allegoryNameUtxoSatoshis: 5555

allegoryTxFeeSatsProducerAction: 400

allegoryTxFeeSatsOwnerAction: 200

txOutputValuesCacheKeyBits: 16

unconfirmedTxCacheKeyBits: 16

getDataResponseTimeout: 30

recentTxReceiveTimeout: 60

blockProcessingTimeout: 120

maxStreamsXCql: 500

stripesXCql: 1

maxConnectionsXCql: 4

maxTxProcessingThreads: 32

maxTxProcessingBuffer: 32

maxInsertsProtocol: 20

blocksFetchWindow: 4

maxBatchProcessingThreads: 100

maxBatchProcessingBuffer: 100
